### ISSUE TITLE
Open to contributions?

### ISSUE THREAD

**Issue by e-enes** [chaun14/invitelogger-api#5]
Hello Team,

I’ve been looking at your project with interest and am considering contributing. Could you please let me know if the project is still active and if you’re open to contributions?

Looking forward to your reply!

Best,
[e.enes](https://github.com/e-enes)

**Comment by chaun14** [comment]
Hello,

The project is still active and in production behind https://api.invitelogger.me  ([documentation](https://developers.invitelogger.me/))
However keep in mind that this api is not linked to the main bot api *yet ?* and there is a lot more work to do 

If you're interested don't hesitate to join my discord server [here](https://discord.gg/CxE6gyT)
